config/routes.rb
Rails.application.routes.draw do
  # == ActiveAdmin
  #
  # Used to set up data
  # management in the backend.
  # Accessible to admins only.
  #
  ActiveAdmin.routes(self)

  # == Static Pages
  #
  root   'guests#index'
  get    'welcome', to: 'guests#welcome'

  #== Authentication
  #
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource  :session,   controller: 'clearance/sessions',  only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get    '/sign_in'        => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out'       => 'sessions#destroy',       as: 'sign_out'
  delete '/admin/sign_out' => 'sessions#destroy',
                              as: 'destroy_admin_user_session'
  get    '/sign_up'        => 'clearance/users#new',    as: 'sign_up'

  # == Core Features ==
  #
  # Resources which give users
  # their main benefits throughout
  # the app.
  #
  #
  #
  #

  # == Logs
  #
  get    'timer', to: 'timers#new'
  resources :timers,    only: %i[new create]
  resources :logs,      only: %i[index new create edit update destroy] do
    resources :replays, only: %i[new create]
  end

  # == Tags
  #
  resources :tags,        only: %i[index new create destroy] do
    member do
      get 'hours_this_day'
    end
  end

  # == Histories
  #
  resources :histories,   only: :index

  # == Conversions
  #
  resources :conversions, only: :show

  # == Sidekiq
  #
  # Set up web interface for
  # background jobs.
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    if signed_in?
      redirect_to timer_path
    else
      redirect_to welcome_path
    end
  end

  def welcome
  end
end

app/views/guests/welcome.html.erb
<section class="mt-4" id="welcome-header">
	<h1 class="display-2">
		TimeTrckr.c<i class="fas fa-clock"></i>m
	</h1>
	<p>The best place to track your time.</p>
</section>
<section class="text-center mt-5">
	<div class="row">
		<div class="col-md-4">
			<span class="fa-stack fa-2x">
				<i class="fas fa-circle fa-stack-2x"></i>
				<i class="fas fa-money-bill-wave fa-stack-1x"></i>
			</span>
			<h2>Save Your Coins</h2>
			<p class="lead">
				It's 100% free, and always will be. No hidden fees or costs.
			</p>
		</div>
		<div class="col-md-4">
			<span class="fa-stack fa-2x">
				<i class="fas fa-circle fa-stack-2x"></i>
				<i class="fas fa-chess-queen fa-stack-1x"></i>
			</span>
			<h2>Keep It Simple</h2>
			<p class="lead">
				Just the right amount of features &mdash; no more, no less.
			</p>
		</div>
		<div class="col-md-4">
			<span class="fa-stack fa-2x">
				<i class="fas fa-circle fa-stack-2x"></i>
				<i class="fas fa-lock fa-stack-1x"></i>
			</span>
			<h2>Safe &amp; Secure</h2>
			<p class="lead">
				Your data is yours and yours only; never shared with or sold to
				3rd parties.
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<span class="fa-stack fa-2x">
				<i class="fas fa-circle fa-stack-2x"></i>
				<i class="fas fa-play fa-stack-1x"></i>
			</span>
			<h2>Sit Back &amp; Relax</h2>
			<p class="lead">
				Click play. Do something productive. Click stop.
				The timer automatically does the heavy-lifting
				for you.
			</p>
		</div>
		<div class="col-md-4">
			<span class="fa-stack fa-2x">
				<i class="fas fa-circle fa-stack-2x"></i>
				<i class="fas fa-plus fa-stack-1x"></i>
			</span>
			<h2>Forgot to Log?</h2>
			<p class="lead">
				No worries, it happens to the best of us. Just let us know
				what you worked on and for how long &mdash; the rest is history.
			</p>
		</div>
		<div class="col-md-4">
			<span class="fa-stack fa-2x">
				<i class="fas fa-circle fa-stack-2x"></i>
				<i class="fas fa-tag fa-stack-1x"></i>
			</span>
			<h2>Go Wild With Tags</h2>
			<p class="lead">
				Organize your logs with as many labels as you'd like (e.g.
				<em>Important</em>, <em>New Feature</em>, <em>Marketing</em>, or
				<em>Busy Work</em>).
			</p>
		</div>
	</div>
</section>
<section class="mt-4">
	<div class="bg-dark p-5 text-center">
		<%= link_to sign_up_path,
								role: "button",
								class: "text-white",
								title: "Sign up now" do %>
			<h1 class="display-4">
				Get Started Now
				<i class="fa fa-sign-in-alt"></i>
			</h1>
		<% end %>
	</div>
	<div class="bg-light p-5 text-center">
		<%= link_to sign_in_path,
								class: "text-dark",
								title: "Sign into TimeTrckr" do %>
			<h4>
				Already have an account? Sign in &raquo;
			</h4>
    <% end %>
  </div>
</section>
<footer class="mt-4 text-center">
	<small>
		<%= mail_to "hello@TimeTrckr.com" %>
		&middot;
		&copy; <%= Date.today.year %>
		TimeTrckr.com
	</small>
</footer>