config/routes.rb
Rails.application.routes.draw do
  # == ActiveAdmin
  #
  # Used to set up data
  # management in the backend.
  # Accessible to admins only.
  #
  ActiveAdmin.routes(self)

  # == Static Pages
  #
  root   'guests#index'
  get    'welcome', to: 'guests#welcome'

  #== Authentication
  #
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource  :session,   controller: 'clearance/sessions',  only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get    '/sign_in'        => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out'       => 'sessions#destroy',       as: 'sign_out'
  delete '/admin/sign_out' => 'sessions#destroy',
                              as: 'destroy_admin_user_session'
  get    '/sign_up'        => 'clearance/users#new',    as: 'sign_up'

  # == Core Features ==
  #
  # Resources which give users
  # their main benefits throughout
  # the app.
  #
  #
  #
  #

  # == Logs
  #
  get    'timer', to: 'timers#new'
  resources :timers,    only: %i[new create]
  resources :logs,      only: %i[index new create edit update destroy] do
    resources :replays, only: %i[new create]
  end

  # == Tags
  #
  resources :tags,        only: %i[index new create destroy] do
    member do
      get 'hours_this_day'
    end
  end

  # == Histories
  #
  resources :histories,   only: :index

  # == Conversions
  #
  resources :conversions, only: :show

  # == Sidekiq
  #
  # Set up web interface for
  # background jobs.
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Associations
  belongs_to :user
  has_many   :logs_tags, dependent: :destroy
  has_many   :logs,      through: :logs_tags

  # Validations
  validates :name, presence: true

  # Scopes
  scope :by_name, -> { order(:name) }

  # == Initializer
  #
  # Build new tag objects from
  # the given comma-separated
  # string
  #
  def self.initializer(user, names)
    names.split(',')
         .reject(&:blank?)
         .uniq
         .map { |name| user.tags.new(name: name) }
  end

  # == Hours This Day (user)
  #
  # Calculate how many hours were
  # spent this day for this tag.
  #
  # @return Decimal
  #
  def hours_this_day(user, log)
    start_date = log.started_at.beginning_of_day
    end_date   = start_date.end_of_day
    user.logs_for_tag(self).where(started_at: start_date..end_date).sum_hours
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login

  def index
    @tags = current_user.tags.by_name
  end

  def new
    @tag = Tag.new
  end

  def create
    raise ActiveRecord::RecordInvalid if tags_params[:name].blank?
    # TODO Refactor into a CreateTagService
    @new_tags = Tag.initializer(current_user, tags_params[:name])
    Tag.transaction do
      @new_tags.each(&:save!)
    end
    flash[:success] = 'Tags successfully created'
    redirect_to tags_path
  end

  def destroy
    @tag = current_user.tags.find(params[:id])
    @tag.destroy!
    flash[:success] = 'Tag successfully removed'
    redirect_to tags_path
  end

  def hours_this_day
    @tag = current_user.tags.find(params[:id])
    @log = current_user.logs.find(params[:log_id])
    @hours_this_day = @tag.hours_this_day(current_user, @log)
    respond_to do |format|
      format.js
    end
  end

  private

  def tags_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_blank_slate.html.erb
<div class="blank-state-message p-3 bg-light">
	<div class="row">
		<div class="col-lg-8 offset-lg-2 text-center">
			<h1>
				You don't have any tags yet:
			</h1>
			<div class="mt-5">
				<h1>
					<%= link_to new_tag_path,
											class: "text-dark",
											title: "Manually create a log" do %>
						<i class="fa fa-plus fa-2x icon-shadow"></i>
						<br>
						Create your first one
					<% end %>
				</h1>
			</div>
		</div>
	</div>
</div>

app/views/tags/_form.html.erb
<%= form_with model: tag do |f| %>
	<div>
		<h1>Give this new tag a name</h1>
		<%= f.label :name, class: "sr-only" %>
		<%= f.text_field :name,
									   class: "form-control",
										 placeholder: "e.g. #{%w[important project1].sample}" %>
		<small class="form-text text-muted">
			Tip: You can create multiple tags with commas like this: tag1, tag2, tag3
		</small>
	</div>
	<div class="mt-4 text-right">
		<%= f.submit "Done", class: "btn btn-dark btn-lg" %>
		<%= link_to "Cancel",
							  tags_path,
								role: "button",
								class: "btn btn-outline-dark btn-lg" %>
	</div>
<% end %>

app/views/tags/_form_tags.html.erb
<div id="form-tags">
	<% tags.each do |tag| %>
		<span class="bubble <%= 'pre-fill' if filled?(log, tag) %>"
		      data-id="<%= tag.id %>">
			<%= tag.name %>
		</span>
	<% end %>
</div>

app/views/tags/_tags.html.erb
<ul class="list-group list-group-flush">
	<% tags.each do |tag| %>
		<li class="list-group-item">
			<span class="bubble">
				<%= tag.name %>
			</span>
			<%= link_to tag_path(tag),
						class: "text-light index",
						title: "Delete this tag",
						method: :delete do %>
				<i class="fas fa-times"></i>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/tags/hours_this_day.js.erb
console.log("<%= @tag.name %> hours for this day: <%= @hours_this_day %>");

app/views/tags/index.html.erb
<section id="tags">
	<% if current_user.tags? %>
		<p class="lead">
			<%= link_to "Create a new tag &raquo;".html_safe,
									new_tag_path,
									title: "Create a new tag to organize your time logs.",
									class: "text-dark" %>
		</p>
		<%= render "tags/tags", tags: @tags %>
	<% else %>
		<%= render "tags/blank_slate" %>
	<% end %>
</section>

app/views/tags/new.html.erb
<section class="new-tag-section">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="mt-4">
				<%= render "tags/form", tag: @tag %>
			</div>
		</div>
	</div>
</section>