config/routes.rb
Rails.application.routes.draw do
  # == ActiveAdmin
  #
  # Used to set up data
  # management in the backend.
  # Accessible to admins only.
  #
  ActiveAdmin.routes(self)

  # == Static Pages
  #
  root   'guests#index'
  get    'welcome', to: 'guests#welcome'

  #== Authentication
  #
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource  :session,   controller: 'clearance/sessions',  only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get    '/sign_in'        => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out'       => 'sessions#destroy',       as: 'sign_out'
  delete '/admin/sign_out' => 'sessions#destroy',
                              as: 'destroy_admin_user_session'
  get    '/sign_up'        => 'clearance/users#new',    as: 'sign_up'

  # == Core Features ==
  #
  # Resources which give users
  # their main benefits throughout
  # the app.
  #
  #
  #
  #

  # == Logs
  #
  get    'timer', to: 'timers#new'
  resources :timers,    only: %i[new create]
  resources :logs,      only: %i[index new create edit update destroy] do
    resources :replays, only: %i[new create]
  end

  # == Tags
  #
  resources :tags,        only: %i[index new create destroy] do
    member do
      get 'hours_this_day'
    end
  end

  # == Histories
  #
  resources :histories,   only: :index

  # == Conversions
  #
  resources :conversions, only: :show

  # == Sidekiq
  #
  # Set up web interface for
  # background jobs.
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/log.rb
class Log < ApplicationRecord
  # Associations
  belongs_to :user
  has_many   :logs_tags,   dependent: :destroy
  has_many   :tags,        through: :logs_tags

  # Validations
  validates :name,         presence: true
  validates :started_at,   presence: true
  validates :stopped_at,   presence: true

  # Scopes
  scope :latest,     -> { order(created_at: :desc) }
  scope :earliest,   -> { order(created_at: :asc) }
  scope :today,      -> {
    where('started_at > ?', Time.current.beginning_of_day)
  }
  scope :this_week,  -> { history }
  scope :last_week,  -> { history(num_weeks_ago: 1) }
  scope :history,  ->(num_weeks_ago: 0) { where(
    'logs.created_at >= ? AND logs.created_at <= ?',
    num_weeks_ago.weeks.ago.beginning_of_week,
    num_weeks_ago.weeks.ago.end_of_week
  )}

  # == Tags?
  #
  # See if this log has any tags.
  #
  # @return Boolean
  #
  def tags?
    tags.any?
  end

  # == Tag? (tag)
  #
  # See if this log has a
  # specific tag.
  #
  # @return Boolean
  #
  def tag?(tag)
    tags.include?(tag)
  end

  # == Hours
  #
  # The number of hours tracked for this
  # log.
  #
  # @return Float
  #
  def hours
    ((stopped_at - started_at) / 1.hour).round(2)
  end

  # == Minutes
  #
  # The number of minutes tracked for this
  # log.
  #
  # @return Float
  #
  def minutes
    (hours * 60).round(0)
  end

  # == Sum Hours
  #
  # The added hours for the chained logs.
  #
  # @return Float
  #
  def self.sum_hours
    select(:started_at, :stopped_at).map(&:hours).sum.round(2)
  end

  # == Hours for Today
  #
  # The number of hours tracked for today.
  #
  # @return Float
  #
  def self.hours_for_today
    today.sum_hours
  end

  # == Convert (unit)
  #
  # Determine the next unit
  # to display:
  # - If hours currently show, switch to
  #   minutes
  # - If minutes currently show, switch
  #   to total hours
  # - If total hours currently show, go
  #   back to hours.
  #
  # @return String
  #
  def self.convert(unit)
    if unit == 'hours'
      'minutes'
    elsif unit == 'minutes'
      'hours_for_today'
    elsif unit == 'hours_for_today'
      'total_hours'
    elsif unit == 'total_hours'
      'hours'
    end
  end

  # == Total Hours
  #
  # Find logs with the same name, i.e.
  # things a user did multiple times,
  # and add all of their hours worked.
  #
  # @return Float
  #
  def total_hours(user)
    user.logs.where(name: name).sum_hours
  end

  # == Hours For Today (user)
  #
  # Find logs with the same name, i.e.
  # things a user did multiple times,
  # and add all of their hours worked
  # for today.
  #
  # @return Float
  #
  def hours_for_today(user)
    user.logs.today.where(name: name).sum_hours
  end

  # == Empty? (logs)
  #
  # See if the given collection
  # has any logs.
  #
  # @return Boolean
  #
  def self.empty?(logs)
    logs.empty?
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :require_login
  before_action :validate_positive_minutes, only: %i[create update]

  def index
    @logs = current_user.logs.today.latest
  end

  def new
    @log = Log.new
    @tags = current_user.tags
  end

  def create
    current_user.logs.create!(log_params)
    flash[:success] = 'Log successfully created'
    redirect_to logs_path
  end

  def edit
    @log = Log.find(params[:id])
    @tags = current_user.tags
  end

  def update
    @log = current_user.logs.find(params[:id])
    update_log_params = log_params.dup
    update_log_params[:started_at] = @log.started_at
    update_log_params[:stopped_at] = @log.started_at + minutes.minutes
    @log.update!(update_log_params)
    flash[:success] = 'Log successfully updated'
    redirect_to logs_path
  end

  def destroy
    current_user.logs.find(params[:id]).destroy!
    flash[:success] = 'Log successfully removed'
    redirect_back(fallback_location: logs_path)
  end

  private

  # == Validate Positive Minutes
  #
  # Ensure minutes is greater
  # than zero.
  #
  # @return Boolean
  #
  def validate_positive_minutes
    raise ActiveRecord::RecordInvalid unless minutes.positive?
  end

  def log_params
    {
      name: params[:log][:name],
      started_at: minutes.minutes.ago,
      stopped_at: Time.current,
      tag_ids: params[:log][:tag_ids]
    }
  end

  def minutes
    params[:log][:minutes].to_i
  end

  def raw_params
    params.permit(:name, :minutes, tag_ids: [])
  end
end

app/helpers/logs_helper.rb
module LogsHelper
	# == Editing Log?
	#
	# See if user is on the
	# logs#edit page.
	#
	# @return Boolean
	#
	def editing_log?
		params[:controller] == 'logs' && params[:action] == 'edit'
	end

	# == Filled? (log, tag)
	#
	# See if a log has the
	# given tag, which will be
	# pre-filled in on the
	# logs#edit page.
	#
	# @return Boolean
	#
  def filled?(log, tag)
    editing_log? && log.tag?(tag)
  end
end

app/views/logs/_actions.html.erb
<%= link_to new_log_replay_path(log),
            class: "text-light index",
            title: "Replay this log",
            remote: true do %>
  <i class="fas fa-play"></i>
<% end %>
<%= link_to edit_log_path(log),
            class: "text-light index",
            title: "Edit this log" do %>
  <i class="fas fa-edit"></i>
<% end %>
<%= link_to log_path(log),
            class: "text-light index",
            title: "Delete this log",
            method: :delete do %>
  <i class="fas fa-times"></i>
<% end %>

app/views/logs/_blank_slate.html.erb
<div class="blank-state-message p-3 bg-light">
	<div class="row">
		<div class="col-lg-8 offset-lg-2 text-center">
			<h1>
				You don't have any logs for <%= text %>:
			</h1>
			<div class="row mt-5">
				<div class="col-md-6">
					<h1>
						<%= link_to timer_path,
												class: "text-dark",
												title: "Go to the Timer" do %>
							<i class="fa fa-play fa-2x icon-shadow"></i>
							<br>
							Automatically track time now
						<% end %>
					</h1>
				</div>
				<div class="col-md-6">
					<h1>
						<%= link_to new_log_path,
												class: "text-dark",
												title: "Manually create a log" do %>
							<i class="fa fa-plus fa-2x icon-shadow"></i>
							<br>
							Log what you already did
						<% end %>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/logs/_form.html.erb
<%= form_with model: log do |f| %>
	<div>
		<h1>What did you do?</h1>
		<%= f.label :name, class: "sr-only" %>
		<%= f.text_field :name,
									   class: "form-control",
										 placeholder: "e.g. Take a 'quick' nap" %>
	</div>
  <div class="mt-5">
		<h1>How many minutes did it take?</h1>
		<%= f.text_field :minutes,
									   class: "form-control",
										 placeholder: "e.g. 112",
										 value: "#{log.minutes if editing_log?}" %>
  </div>
	<%= render "tags/form_tags", log: log, tags: tags %>
	<div class="mt-4 text-right">
		<%= f.submit "#{btn_text}", class: "btn btn-dark btn-lg" %>
		<%= link_to "Cancel",
							  timer_path,
								role: "button",
								class: "btn btn-outline-dark btn-lg" %>
	</div>
<% end %>

app/views/logs/_logs.html.erb
<ul>
	<% logs.each do |log| %>
		<li>
			<div>
				<div class="log-time">
					<b data-log-id="<%= log.id %>">
						<%= link_to "#{log.hours}h",
												conversion_path(log, unit: 'hours'),
												class: "text-dark",
												remote: true %>
					</b>
				</div>
				<div class="log-name"><%= log.name %></div>
				<div class="log-tags">
					<%= render "logs/tags", log: log %>
				</div>
				<div class="log-actions">
					<%= render "logs/actions", log: log %>
				</div>
			</div>
		</li>
	<% end %>
</ul>

app/views/logs/_tags.html.erb
<% if log.tags? %>
	<% log.tags.by_name.each do |tag| %>
	  <%= link_to hours_this_day_tag_path(tag, log_id: log),
								remote: true do %>
			<span class="bubble">
					<%= tag.name %>
			</span>
		<% end %>
	<% end %>
<% end %>

app/views/logs/edit.html.erb
<section class="logs-section">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="mt-4">
				<%= render "logs/form",
									 log: @log,
									 tags: @tags,
									 btn_text: "Update log" %>
			</div>
		</div>
	</div>
</section>

app/views/logs/index.html.erb
<section id="logs">
	<% if current_user.logs_today? %>
		<p class="lead">
			<%= current_user.hours_for_today %> hours logged today
		</p>
		<%= render "logs/logs", logs: @logs %>
	<% else %>
		<%= render "logs/blank_slate", text: "today" %>
	<% end %>
</section>

app/views/logs/new.html.erb
<section class="new-log-section">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="mt-5">
				<%= render "logs/form", log: @log %>
			</div>
		</div>
	</div>
</section>