config/routes.rb
Rails.application.routes.draw do
  # == ActiveAdmin
  #
  # Used to set up data
  # management in the backend.
  # Accessible to admins only.
  #
  ActiveAdmin.routes(self)

  # == Static Pages
  #
  root   'guests#index'
  get    'welcome', to: 'guests#welcome'

  #== Authentication
  #
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource  :session,   controller: 'clearance/sessions',  only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get    '/sign_in'        => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out'       => 'sessions#destroy',       as: 'sign_out'
  delete '/admin/sign_out' => 'sessions#destroy',
                              as: 'destroy_admin_user_session'
  get    '/sign_up'        => 'clearance/users#new',    as: 'sign_up'

  # == Core Features ==
  #
  # Resources which give users
  # their main benefits throughout
  # the app.
  #
  #
  #
  #

  # == Logs
  #
  get    'timer', to: 'timers#new'
  resources :timers,    only: %i[new create]
  resources :logs,      only: %i[index new create edit update destroy] do
    resources :replays, only: %i[new create]
  end

  # == Tags
  #
  resources :tags,        only: %i[index new create destroy] do
    member do
      get 'hours_this_day'
    end
  end

  # == Histories
  #
  resources :histories,   only: :index

  # == Conversions
  #
  resources :conversions, only: :show

  # == Sidekiq
  #
  # Set up web interface for
  # background jobs.
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_head.html.erb
<head>
	<%= render "shared/google_analytics" %>
	<meta name="viewport"  content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="author"    content="Danelson Rosa">
	<meta name="webmaster" content="Danelson Rosa">
	<meta name="copyright" content="Danelson Rosa">
	<meta name="description" content="Manage your time with our easy-to-use (no, really!), free software.">
	<meta name="application-name" content="TimeTrckr.com">
	<meta name="keywords" content="track your time, easy way to track time, organize your time, simple time tracking software, free time tracker, online timer, timesheets">

	<title>
		TimeTrckr.com &mdash; free time tracking software to manage your time
	</title>

	<link rel="canonical" href="https://timetrckr.com">

	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= stylesheet_link_tag    'https://use.fontawesome.com/releases/v5.3.1/css/all.css' %>
	<%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_navbar.html.erb
<div class="navbar">
	<div class="todays-date">
		<h1><%= link_to "#{today}", logs_path, class: "text-dark" %></h1>
	</div>
	<ul class="links">
		<li>
			<%= link_to timer_path, 
						class: "text-dark", 
						title: "Go to the Timer" do %>
				<i class="fa fa-play"></i>
			<% end %>
		</li>
		<li>
			<%= link_to new_log_path,
						class: "text-dark",
						title: "Manually create a log" do %>
				<i class="fa fa-plus"></i>
			<% end %>
		</li>
		<li>
			<%= link_to tags_path,
						class: "text-dark",
						title: "View your tags" do %>
				<i class="fa fa-tag"></i>
			<% end %>
		</li>
		<li>
			<% if signed_in? %>
				<%= link_to sign_out_path,
								class: "text-dark",
								title: "Sign out",
								method: :delete do %>
					<i class="fa fa-sign-out-alt"></i>
				<% end %>
			<% else %>
				<%= link_to sign_in_path,
							class: "text-dark",
							title: "Sign in" do %>
					<i class="fa fa-sign-in-alt"></i>
				<% end %>
			<% end %>
		</li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>
    <div class="main-wrapper">
      <%= render "shared/flash_messages" %>
      <% if signed_in? %>
        <%= render "layouts/navbar" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>